export { client } from "./client";
export { urlFor } from "./image";
export { getFeaturedMerch, getAllMerch, type MerchItemForUI } from "./merch";
export {
  getFeaturedProjects,
  getProjects,
  getYearsWithProjectIds,
  type ProjectForUI,
  type YearWithProjectIds,
} from "./projects";
export {
  getPhotoGallery,
  type PhotoGalleryForUI,
  type YearWithProjectsForUI,
  type ProjectForGalleryPicker,
  type GalleryItemForUI,
} from "./photoGallery";
export {
  getFinfestGallery,
  type FinfestGalleryForUI,
  type FinfestGalleryYearForUI,
} from "./finfestGallery";

// Generated by Sanity TypeGen (run from studio: pnpm run typegen)
export type {
  Project,
  ProjectsQueryResult,
  FeaturedProjectsQueryResult,
  AllSanitySchemaTypes,
} from "./sanity.types";

export {
  getBlogs,
  getBlogBySlug,
  type BlogForUI,
  type BlogDetailForUI,
} from "./blogs";
