export { client } from "./client";
export { urlFor } from "./image";
export {
  getFeaturedProjects,
  getProjects,
  getYearsWithProjectIds,
  type ProjectForUI,
  type YearWithProjectIds,
} from "./projects";
export {
  getPhotoGallery,
  type PhotoGalleryForUI,
  type YearWithProjectsForUI,
  type ProjectForGalleryPicker,
  type GalleryItemForUI,
} from "./photoGallery";

// Generated by Sanity TypeGen (run from studio: pnpm run typegen)
export type {
  Project,
  ProjectsQueryResult,
  FeaturedProjectsQueryResult,
  AllSanitySchemaTypes,
} from "./sanity.types";
