/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type PastSpeaker = {
  _id: string;
  _type: "pastSpeaker";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  role?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Merch = {
  _id: string;
  _type: "merch";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  price?: number;
  category?: string;
  inStock?: boolean;
  featured?: boolean;
  storeUrl?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Blog = {
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  authorImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  authorName?: string;
  excerpt?: string;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      }
  >;
  readTime?: number;
  tags?: Array<string>;
  featured?: boolean;
  publishedDate?: string;
};

export type ProjectReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "project";
};

export type Year = {
  _id: string;
  _type: "year";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  year?: number;
  projects?: Array<
    {
      _key: string;
    } & ProjectReference
  >;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type GalleryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "gallery";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  previewMedia?: {
    type?: "image" | "video";
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    video?: {
      asset?: SanityFileAssetReference;
      media?: unknown;
      _type: "file";
    };
  };
  details?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  additionalImages?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  country?: string;
  featured?: boolean;
  isOngoing?: boolean;
  gallery?: GalleryReference;
};

export type Gallery = {
  _id: string;
  _type: "gallery";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  year?: number;
  items?: Array<{
    type?: "image" | "video";
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    video?: {
      asset?: SanityFileAssetReference;
      media?: unknown;
      _type: "file";
    };
    caption?: string;
    useAsThumbnail?: boolean;
    _type: "mediaItem";
    _key: string;
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | PastSpeaker
  | SanityImageCrop
  | SanityImageHotspot
  | Merch
  | Slug
  | Blog
  | ProjectReference
  | Year
  | SanityFileAssetReference
  | GalleryReference
  | Project
  | Gallery
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/lib/sanity/queries/blogs.ts
// Variable: blogsQuery
// Query: *[_type == "blog" && (!defined($currentSlug) || slug.current != $currentSlug)] | order(publishedDate desc) {    _id,    title,    "slug": slug.current,    excerpt,    readTime,    publishedDate,    "mainImage": mainImage.asset->url  }
export type BlogsQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  readTime: number | null;
  publishedDate: string | null;
  mainImage: string | null;
}>;

// Source: ../web/lib/sanity/queries/blogs.ts
// Variable: blogBySlugQuery
// Query: *[_type == "blog" && slug.current == $slug][0] {  _id,  title,  "slug": slug.current,  excerpt,  body,  readTime,  publishedDate,  "mainImage": mainImage.asset->url,  authorName,  "authorImage": authorImage.asset->url}
export type BlogBySlugQueryResult = {
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      }
  > | null;
  readTime: number | null;
  publishedDate: string | null;
  mainImage: string | null;
  authorName: string | null;
  authorImage: string | null;
} | null;

// Source: ../web/lib/sanity/queries/finfestGallery.ts
// Variable: finfestGalleryQuery
// Query: *[_type == "gallery" && slug.current match "finfest*" && defined(year)] | order(year desc) {  _id,  title,  year,  "items": items[] {    type,    useAsThumbnail,    "imageRef": image.asset->,    "videoUrl": video.asset->url,    caption  }}
export type FinfestGalleryQueryResult = Array<{
  _id: string;
  title: string | null;
  year: number | null;
  items: Array<{
    type: "image" | "video" | null;
    useAsThumbnail: boolean | null;
    imageRef: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    } | null;
    videoUrl: string | null;
    caption: string | null;
  }> | null;
}>;

// Source: ../web/lib/sanity/queries/merch.ts
// Variable: featuredMerchQuery
// Query: *[_type == "merch" && featured == true] | order(_createdAt desc)[0...6] {  _id,  title,  "slug": slug.current,  "coverImage": coverImage {    alt,    "asset": asset->  },  price,  category,  inStock,  storeUrl}
export type FeaturedMerchQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  coverImage: {
    alt: string | null;
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    } | null;
  } | null;
  price: number | null;
  category: string | null;
  inStock: boolean | null;
  storeUrl: string | null;
}>;

// Source: ../web/lib/sanity/queries/merch.ts
// Variable: allMerchQuery
// Query: *[_type == "merch"] | order(_createdAt desc) {  _id,  title,  "slug": slug.current,  "coverImage": coverImage {    alt,    "asset": asset->  },  price,  category,  inStock,  storeUrl}
export type AllMerchQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  coverImage: {
    alt: string | null;
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    } | null;
  } | null;
  price: number | null;
  category: string | null;
  inStock: boolean | null;
  storeUrl: string | null;
}>;

// Source: ../web/lib/sanity/queries/past-speaker.ts
// Variable: pastSpeakersQuery
// Query: *[_type == "pastSpeaker"] | order(_createdAt asc) {    _id,    name,    role,    "image": image.asset->url  }
export type PastSpeakersQueryResult = Array<{
  _id: string;
  name: string | null;
  role: string | null;
  image: string | null;
}>;

// Source: ../web/lib/sanity/queries/photoGallery.ts
// Variable: yearsWithProjectsForGalleryQuery
// Query: *[_type == "year"] | order(year desc) {  year,  "projects": projects[]-> {    _id,    title,    description,    "previewMedia": previewMedia {      type,      "imageRef": image.asset->,      "videoUrl": video.asset->url    },    "gallery": gallery-> {      "items": items[] {        type,        useAsThumbnail,        "imageRef": image.asset->,        "videoUrl": video.asset->url,        caption      }    }  }}
export type YearsWithProjectsForGalleryQueryResult = Array<{
  year: number | null;
  projects: Array<{
    _id: string;
    title: string | null;
    description: string | null;
    previewMedia: {
      type: "image" | "video" | null;
      imageRef: {
        _id: string;
        _type: "sanity.imageAsset";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        originalFilename?: string;
        label?: string;
        title?: string;
        description?: string;
        altText?: string;
        sha1hash?: string;
        extension?: string;
        mimeType?: string;
        size?: number;
        assetId?: string;
        uploadId?: string;
        path?: string;
        url?: string;
        metadata?: SanityImageMetadata;
        source?: SanityAssetSourceData;
      } | null;
      videoUrl: string | null;
    } | null;
    gallery: {
      items: Array<{
        type: "image" | "video" | null;
        useAsThumbnail: boolean | null;
        imageRef: {
          _id: string;
          _type: "sanity.imageAsset";
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          originalFilename?: string;
          label?: string;
          title?: string;
          description?: string;
          altText?: string;
          sha1hash?: string;
          extension?: string;
          mimeType?: string;
          size?: number;
          assetId?: string;
          uploadId?: string;
          path?: string;
          url?: string;
          metadata?: SanityImageMetadata;
          source?: SanityAssetSourceData;
        } | null;
        videoUrl: string | null;
        caption: string | null;
      }> | null;
    } | null;
  }> | null;
}>;

// Source: ../web/lib/sanity/queries/projects.ts
// Variable: projectsQuery
// Query: *[_type == "project"] | order(_createdAt desc) {  _id,  title,  "slug": slug.current,  description,  country,  featured,  "previewMedia": previewMedia {    type,    "imageRef": image.asset->,    "videoUrl": video.asset->url  }}
export type ProjectsQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  description: string | null;
  country: string | null;
  featured: boolean | null;
  isOngoing: boolean | null;
  previewMedia: {
    type: "image" | "video" | null;
    imageRef: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    } | null;
    videoUrl: string | null;
  } | null;
}>;

// Source: ../web/lib/sanity/queries/projects.ts
// Variable: featuredProjectsQuery
// Query: *[_type == "project" && featured == true] | order(_createdAt desc) {  _id,  title,  "slug": slug.current,  description,  country,  featured,  "previewMedia": previewMedia {    type,    "imageRef": image.asset->,    "videoUrl": video.asset->url  }}
export type FeaturedProjectsQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  description: string | null;
  country: string | null;
  featured: true;
  isOngoing: boolean | null;
  previewMedia: {
    type: "image" | "video" | null;
    imageRef: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    } | null;
    videoUrl: string | null;
  } | null;
}>;

// Source: ../web/lib/sanity/queries/projects.ts
// Variable: featuredCountryProjectsQuery
// Query: *[_type == "project" && country == $country && featured == true] | order(_createdAt desc) {  _id,  title,  "slug": slug.current,  description,  country,  featured,  "previewMedia": previewMedia {    type,    "imageRef": image.asset->,    "videoUrl": video.asset->url  }}
export type FeaturedCountryProjectsQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  description: string | null;
  country: string | null;
  featured: boolean | null;
  isOngoing: boolean | null;
  previewMedia: {
    type: "image" | "video" | null;
    imageRef: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    } | null;
    videoUrl: string | null;
  } | null;
}>;

// Source: ../web/lib/sanity/queries/projects.ts
// Variable: yearsWithProjectIdsQuery
// Query: *[_type == "year"] | order(year desc) {  year,  "projectIds": projects[]->_id}
export type YearsWithProjectIdsQueryResult = Array<{
  year: number | null;
  projectIds: Array<string> | null;
}>;

// Source: ../web/lib/sanity/queries/projects.ts
// Variable: projectBySlugQuery
// Query: *[_type == "project" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    description,    country,    featured,    "previewMedia": previewMedia {      type,      "imageRef": image.asset->,      "videoUrl": video.asset->url    },    details,    "additionalImages": additionalImages[]{      asset->    },  }
export type ProjectBySlugQueryResult = {
  _id: string;
  title: string | null;
  slug: string | null;
  description: string | null;
  country: string | null;
  featured: boolean | null;
  isOngoing: boolean | null;
  previewMedia: {
    type: "image" | "video" | null;
    imageRef: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    } | null;
    videoUrl: string | null;
  } | null;
  details: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  additionalImages: Array<{
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    } | null;
  }> | null;
} | null;
